import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {

  
  return (
    <html lang="en">
    <body className={inter.className}>
    <div className='sidenav'>
        <a href="/" >Home</a>
        <a href="/about" >About</a>
        <a href="/events" >Events</a>
        <a href="/communities" >communities</a>
        <a href="/message" >Message</a>
    </div>
    <main>{children}</main>
    </body>
  </html>
)
}
