import Link from 'next/link'
import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {

  
  return (
    <html lang="en">
    <body className={inter.className}>
    <div className='sidenav'>
        <Link href="/" >Home</Link>
        <Link href="/about" >About</Link>
        <Link href="/events" >Events</Link>
        <Link href="/communities" >communities</Link>
        <Link href="/message" >Message</Link>
    </div>
    <main>{children}</main>
    </body>
  </html>
)
}
