import "./globals.css";
import { Inter } from "next/font/google";
import NavMenu from "./NavMenu";
import AuthProvider from "./AuthProvider";
import Header from "./Header";
import Head from "next/head";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <AuthProvider>
      <html lang="en">
        <body className={inter.className}>
          <Head>
            <meta name="viewport" content="viewport-fit=cover" />
          </Head>
          <Header />
          <div className="layout-container">
            <NavMenu />
            <div className="layout-content">{children}</div>
          </div>
        </body>
      </html>
    </AuthProvider>
  );
}
